#!/usr/bin/env bash
set -e
set -o errexit

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-}")" &>/dev/null && pwd 2>/dev/null)"
exampleOutputFile="$here/../dist/exampleConfig.bash"
pluginsOutputFile="$here/../dist/plugins.bash"
pluginsFolder="$here/../plugins"
listFile="$here/../etc/list.bash"
configFile="$here/../etc/config.bash"

source "$listFile"

printf '' >"$pluginsOutputFile"

for pluginName in "${plugins[@]}"; do
  cat "$pluginsFolder/$pluginName.bash" >>"$pluginsOutputFile"
  echo "" >>"$pluginsOutputFile"
done

cp "$pluginsOutputFile" "$exampleOutputFile"

echo "print_info() {
  info model
  info underline" >>"$exampleOutputFile"

for i in "${!plugins[@]}"; do
  printf '  info "%s" %s # https://github.com/Jaid/neofetch-plugins/blob/main/dist/plugins/%s.bash\n' "${pluginLabels[$i]}" "${plugins[$i]}" "${plugins[$i]}" >>"$exampleOutputFile"
done

echo '  info cols
}
' >>"$exampleOutputFile"

cat "$configFile" >>"$exampleOutputFile"
